# Generated by Django 4.2.7 on 2023-11-14 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=50)),
                ('asunto', models.TextField(max_length=2000)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=11)),
                ('tipo_de_mensaje', models.CharField(choices=[('SC', 'Solicitud de Cotización'), ('C', 'Consulta'), ('S', 'Sugerencia'), ('F', 'Felicitaciones')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudCotizacion',
            fields=[
                ('mensaje_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_cotizaciones.mensaje')),
                ('tipo_de_evento', models.CharField(choices=[('A', 'Matrimonio'), ('B', 'Cumpleaños'), ('C', 'Cheese and Wine'), ('D', 'Gala 4to Medio')], max_length=3)),
                ('cantidad_de_personas', models.IntegerField()),
                ('servicios', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField()),
            ],
            bases=('gestor_cotizaciones.mensaje',),
        ),
    ]
