# Generated by Django 4.2.7 on 2023-11-14 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del producto')),
                ('unidad_de_medida', models.CharField(choices=[('Kg', 'Kilogramos'), ('u.', 'unidades'), ('g', 'gramos'), ('L', 'Litros'), ('ml', 'mililitros')], max_length=2)),
                ('stock', models.FloatField()),
                ('proveedor', models.CharField(blank=True, max_length=30, verbose_name='Nombre de proveedor')),
                ('precio_venta_unidad', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('unidad_de_medida', models.CharField(choices=[('DD', 'Dias'), ('hh', 'Horas'), ('u.', 'unidades')], max_length=2)),
                ('valor_por_unidad', models.FloatField()),
            ],
        ),
    ]
