# Generated by Django 4.2.7 on 2023-11-14 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('tipo_evento', models.CharField(max_length=30)),
                ('cantidad_personas', models.IntegerField()),
                ('inicio', models.DateTimeField()),
                ('termino', models.DateTimeField()),
            ],
        ),
    ]
